---
title: "Analytics>Forward 2019"
author: "Rick Pack"
date: "February 27, 2019"
# output: html_document
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE)
## Save files locally?
save_to_folder <- TRUE
## If TRUE, where to save?
folder_save <- "C:/Users/rick2/Downloads/R/AnalyticsForward_2019/"
####################################
## If need to use github CSV file ##
## rather than use Meetup API     ##
####################################
github_file <- FALSE
github_filename <- 'C:/Users/rick2/Downloads/AnalyticsForward_2019/AnalyticsForward_2019_02_27_AM.csv'

# Get your Meetup key by going to
  # https://secure.meetup.com/meetup_api/key/
  # Sys.setenv(MEETUP_KEY = "NOT_SHOWN")
  
  # What is the Meetup group name?
  # Find this in the Meetup URL.
  # For example, in https://www.meetup.com/Research-Triangle-Analysts/events/258165094/
  # it is:
  # 'Research-Triangle-Analysts'
  meetupgrp_name <- 'Research-Triangle-Analysts'

###################################
## If using the API, save files  ##
## with AM or PM (or anything)   ##
## suffix?                       ##
AMPM <- "AM"


source('Meetup_RSVP_Yes_20190227.R')

```

## "Analytics>Forward" (2019) - 5th annual unconference by Research Triangle Analysts

Files for Analytics>Forward 2019 by Research Triangle Analysts - "Pitch a talk, hear some talks" #AnalyticsForward http://bit.ly/AF2019Signup

```{r af_2019}
print(p1)
print(p2)
print(p3)
print(p4)
print(p5)
print(grp_plot)
print(grp_plot_latestyear)
```

```{r tables}
message("Total registrations")
knitr::kable(allAF_frm %>% group_by(yes_year) %>% 
  dplyr::filter(dates_yes == max(dates_yes)) %>%
  select(id_name, yes_year, dates_yes_cumsum))